---
production:
  adapter: mysql2
  username: wagn_dev
  database: cha_dev
  host: localhost
  sesson_key: wagn_production
  password: wdev_p8p9
  secret: YrDOGOmYJyFg2xTZykC5ZjWYQUbKBt
development:
  session_key: wagn_development
  adapter: mysql2
  username: wagn_dev
  database: cha_dev
  host: localhost
  password: wdev_p8p9
  secret: YrDOFOmYJyFg2tTZykCbZjWYQUbKBt
cucumber:
  session_key: wagn_test
  adapter: mysql2
  username: wagn_dev
  database: cha_test
  host: localhost
  password: wdev_p8p9
  secret: YrDOFOmYJyFg2tTZykCbZjWYQUbKBt
test:
  session_key: wagn_test
  adapter: mysql2
  username: wagn_dev
  database: cha_test
  host: localhost
  password: wdev_p8p9
  secret: YrDOFOmYJyFg2tTZykCbZjWYQUbKBt
